Initial commit of NOPE tool
openshift-qe/ocp-qe-perfscale-ci pull request #135
Opened 2022-05-03 21:13 UTC by nathan-weinberg

This PR:
- Creates an initial skeleton of the NOPE tool
- Adds a `requirements.txt` file for the NOPE tool dependencies
- Updates `README.md` with details about the NOPE tool
- Updates `.gitignore` to prevent performance data from being pushed to GitHub
- Resolves https://issues.redhat.com/browse/NETOBSERV-327

2022-05-03 21:14 UTC, nathan-weinberg commented
/cc @mffiedler @paigerube14 @memodi

2022-05-04 16:46 UTC, paigerube14 commented on scripts/nope.py
> +	TOKEN = args.token
might be nice here to set a default value by getting response of _oc whoami -t_ but if the user does pass the -t option to overwrite default. Same with CLUSTER_URL. Thoughts?

2022-05-04 16:48 UTC, memodi requested changes

2022-05-04 16:48 UTC, memodi commented on scripts/nope_requirements.txt
> +argparse==1.4.0
change filename to be requirements.txt

2022-05-04 16:54 UTC, paigerube14 commented on scripts/nope.py
> +CPU_QUERY = 'pod:container_cpu_usage:sum{namespace="network-observability"}'
maybe we can add namespace as a parameter we pass in so this script can be more versatile and be used in any namespace.

2022-05-04 16:55 UTC, paigerube14 commented on scripts/nope.py
> +LOKI_QUERY = 'kubelet_volume_stats_used_bytes{namespace="network-observability", persistentvolumeclaim="loki-store"}'
I'm not exactly sure about how NO is set up, but maybe we should add in a check to see if the loki-store pvc is on the cluster before running this query? Trying now on my cluster that that's not set up and seeing how it would react

2022-05-04 17:00 UTC, paigerube14 commented on scripts/nope.py
> +	if query_type == "cpu":
Thoughts on making this set up a 2d list or dictionary that we could loop through. 

Ex.) Dictionary set up 
query_list = { {name: cpu, query: CPU_QUERY},  {name: mem, query: MEM_QUERY}, {name: loki, query: LOKI_QUERY}}

Not sure if you really need the name key value here. 

```
for ql in query_list: 
  params = {'query': ql['query']}
  requests... 
```

2022-05-04 17:04 UTC, paigerube14 commented on scripts/nope.py
> +
Mehul copied my thoughts exactly. But definitely think we need start and end time here as well!

2022-05-04 17:36 UTC, memodi commented on scripts/nope.py
> +LOKI_QUERY = 'kubelet_volume_stats_used_bytes{namespace="network-observability", persistentvolumeclaim="loki-store"}'
yeah, it's something user has to deploy manually as PVC kind.  
For this tool to be versatile, we'll probably need to develop more or less a framework with some libraries/classes where user could add define all the metrics and methods to be collected and the script (for e.g.: netobserv.py) will simply call appropriate class based on argument and desired class.

2022-05-04 17:37 UTC, memodi commented on scripts/nope.py
> +CPU_QUERY = 'pod:container_cpu_usage:sum{namespace="network-observability"}'
that a great idea @paigerube14 , see my comment here https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/135#discussion_r865103368 , let me know what you and @nathan-weinberg think.

2022-05-04 17:43 UTC, nathan-weinberg commented on scripts/nope.py
> +	if query_type == "cpu":
@paigerube14 I like the idea, but I think it might be over-engineering for right now

2022-05-04 17:46 UTC, nathan-weinberg commented on scripts/README.md
> +2. Install requirements with `pip install -r scripts/nope_requirements.txt`
Yes will do

2022-05-04 17:48 UTC, nathan-weinberg commented on scripts/nope.py
> +	TOKEN = args.token
Similar to https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/135#discussion_r865051600 - let's discuss there

2022-05-04 17:50 UTC, paigerube14 commented on scripts/nope.py
> +CPU_QUERY = 'pod:container_cpu_usage:sum{namespace="network-observability"}'
yep exactly what I was thinking, make network-observability default but add optional argument to pass other namespaces

2022-05-04 17:51 UTC, nathan-weinberg commented on scripts/nope.py
> +
@paigerube14 @memodi So basically this is a scoping question - do we want assume users have set `kubeconfig` and logged into the cluster as `kubeadmin` **prior** to running the tool? If we make this a requirement, we can programmatically extract both of these arguments - I do like the idea. I would like to implement this as a followup if that is alright with you both, so we can get the tool merged and begin using it. I reckon I could get this done later this week or next. Let me know your thoughts in this thread, in the meantime I will push up other suggested changes.

2022-05-04 17:53 UTC, memodi commented on scripts/nope.py
> +CPU_QUERY = 'pod:container_cpu_usage:sum{namespace="network-observability"}'
even for network-observability, there's nothing stopping for being deployed in different NS other than `network-observability` , so +1 for making NS configurable. thanks!

2022-05-04 17:56 UTC, nathan-weinberg commented on scripts/nope.py
> +CPU_QUERY = 'pod:container_cpu_usage:sum{namespace="network-observability"}'
I will update the PR to do this @paigerube14 @memodi - thanks!

2022-05-04 18:06 UTC, memodi commented on scripts/nope.py
> +LOKI_QUERY = 'kubelet_volume_stats_used_bytes{namespace="network-observability", persistentvolumeclaim="loki-store"}'
I am fine changing at later stage, it would be lot of refactoring though because it would be more or less a design change.

2022-05-04 18:08 UTC, memodi commented on scripts/nope.py
> +
Yes, it's fine with that assumption for now and already noted in README, so we should be good for this PR and come back later.

2022-05-04 18:56 UTC, paigerube14 commented on scripts/README.md
> +1. Ensure you have Python 3.9+ and Pip installed (verify with `python --version` and `pip --version`)
is 3.9 necessary for this tool? Think in the jenkinsfile we specifically create python3.8.12 virtualenv.  I know we have hit a lot of issues with not being able to change the specific python version on Jenkins. That's why we do this: https://github.com/openshift-qe/ocp-qe-perfscale-ci/blob/f1199c911417a946c52197a560b527d4203cdb17/Jenkinsfile#L157

2022-05-04 19:04 UTC, nathan-weinberg commented on scripts/README.md
> +1. Ensure you have Python 3.9+ and Pip installed (verify with `python --version` and `pip --version`)
Yes, there are 3.9 specific functions being used here - we'll have to change the above line, thanks for pointing this out. @memodi ^^

2022-05-04 19:09 UTC, memodi commented on scripts/README.md
> +1. Ensure you have Python 3.9+ and Pip installed (verify with `python --version` and `pip --version`)
@nathan-weinberg - could you point out what is python 3.9 specific in this PR?

2022-05-04 19:13 UTC, nathan-weinberg commented on scripts/README.md
> +1. Ensure you have Python 3.9+ and Pip installed (verify with `python --version` and `pip --version`)
https://docs.python.org/3/library/stdtypes.html#str.startswith

2022-05-04 19:13 UTC, nathan-weinberg commented on scripts/README.md
> +1. Ensure you have Python 3.9+ and Pip installed (verify with `python --version` and `pip --version`)
was introduced in 3.9

2022-05-04 19:18 UTC, paigerube14 commented on scripts/README.md
> +3. Run the tool with `./scripts/nope.py` with the `--url` arg being your cluster's URL and the `--token` arg being your token for Bearer authentication. You can get the token by logging into your clu
maybe adding a suggestion on how to get cluster_url similar to what you did for the token in this description

2022-05-04 19:23 UTC, memodi commented on scripts/README.md
> +1. Ensure you have Python 3.9+ and Pip installed (verify with `python --version` and `pip --version`)
okay, sounds good. I'll update Jenkinsfile to 3.9.12

2022-05-04 19:34 UTC, memodi commented
/lgtm

2022-05-04 19:35 UTC, paigerube14 commented
/lgtm

2022-05-04 19:37 UTC, merged