Added netobserv operator data to JSON payload
openshift-qe/ocp-qe-perfscale-ci pull request #168
Opened 2022-05-27 13:36 UTC by nathan-weinberg

Resolves [NETOBSERV-375](https://issues.redhat.com/browse/NETOBSERV-375)

2022-05-27 13:36 UTC, nathan-weinberg commented
/cc @memodi

2022-05-27 13:43 UTC, nathan-weinberg commented
Example of data being generated:
```
    "netobservEnv": {
        "release": "main",
        "flp_kind": "DaemonSet",
        "loki_pvc_cap": "1Gi",
        "agent": "ipfix",
        "sampling": "400",
        "cache_active_time": "60s",
        "cache_max_flows": "100"
    }
```

2022-05-31 16:24 UTC, memodi requested changes
requesting changes for error handling and extensible use case.

2022-05-31 16:24 UTC, memodi commented on scripts/nope.py
> +		info[command] = subprocess.run(base_commands[command], capture_output=True, text=True).stdout[1:-1]
I would suggest to check stderr as well in case of errors before checking for stdout.

2022-05-31 16:24 UTC, memodi commented on scripts/nope.py
> +		info[command] = subprocess.run(agent_commands[command], capture_output=True, text=True).stdout[1:-1]
same comment as above for error checking.
> I would suggest to check stderr as well in case of errors before checking for stdout.

2022-05-31 16:24 UTC, memodi commented on scripts/nope.py
> +def get_operator_info():
suggest naming this function as: `get_netobserv_env_info` to resemble what it's doing specifically.

2022-05-31 16:24 UTC, memodi commented on scripts/nope.py
> +	RESULTS["netobservEnv"] = get_operator_info()
since we're trying to have this tool extensible for other use cases as well. We should probably have an extra argument to fetch environment info and that argument could hold a `str` value, for e.g.: "netobserv". Internally in code, we could maintain a dictionary of all the environment that it supports with key as str and value as function name, for e.g.: {"netobserv":  "get_netobserv_env_info"}. So, whenever user wishes to grab particular env. info, appropriate function can be called based on user argument that was provided.

2022-05-31 17:12 UTC, nathan-weinberg commented on scripts/nope.py
> +	RESULTS["netobservEnv"] = get_operator_info()
The code will fail well before this step if KUBECONFG is not set - if we are going to do checks, it should be done prior to the argument parsing. I can introduce a function to do this validation, not necessarily related to this task but we can piggy-back it onto this PR.

2022-05-31 17:16 UTC, paigerube14 commented on scripts/nope.py
> +		info[command] = subprocess.run(agent_commands[command], capture_output=True, text=True).stdout[1:-1]
It looks like you are doing the same functionality a couple of times (calling subprocess and getting certain output), maybe this would be good in a function and call it instead

2022-05-31 17:25 UTC, nathan-weinberg commented on scripts/nope.py
> +	RESULTS["netobservEnv"] = get_operator_info()
Let's hold off until doing this until we have an actual other usecase to test, I don't want to overengineer things in the meantime

2022-05-31 19:02 UTC, paigerube14 commented
Looks good to me, not commenting to let Mehul verify the script itself

2022-05-31 19:16 UTC, merged