Added benchmark env info to data JSON
openshift-qe/ocp-qe-perfscale-ci pull request #176
Opened 2022-06-03 17:28 UTC by nathan-weinberg

Also did minor reformats/additons to general NOPE code and scripts README

Example of new benchmark env data using `--jenkins-job scale-ci/e2e-benchmarking-multibranch-pipeline/kube-burner` and `--jenkins-build 491`:
```json
"benchmarkEnv": {
        "uuid": "09023530-a327-4c1c-bb23-ab877d6ee40b",
        "jenkins_job_params": [
            {
                "_class": "hudson.model.StringParameterValue",
                "name": "BUILD_NUMBER",
                "value": "108879"
            },
            {
                "_class": "hudson.model.StringParameterValue",
                "name": "WORKLOAD",
                "value": "node-density-heavy"
            },
            {
                "_class": "hudson.model.BooleanParameterValue",
                "name": "WRITE_TO_FILE",
                "value": true
            },
            {
                "_class": "hudson.model.StringParameterValue",
                "name": "JENKINS_AGENT_LABEL",
                "value": "oc411"
            },
            {
                "_class": "hudson.model.StringParameterValue",
                "name": "VARIABLE",
                "value": "200"
            },
            {
                "_class": "jenkins.plugins.parameter_separator.ParameterSeparatorValue",
                "name": "NODE_DENSITY_JOB_INFO"
            },
            {
                "_class": "hudson.model.StringParameterValue",
                "name": "NODE_COUNT",
                "value": "7"
            },
            {
                "_class": "jenkins.plugins.parameter_separator.ParameterSeparatorValue",
                "name": "CONCURRENT_BUILDS_JOB_INFO"
            },
            {
                "_class": "hudson.model.StringParameterValue",
                "name": "BUILD_LIST",
                "value": "1 8 15 30 45 60 75"
            },
            {
                "_class": "hudson.model.StringParameterValue",
                "name": "APP_LIST",
                "value": "cakephp eap django nodejs"
            },
            {
                "_class": "hudson.model.StringParameterValue",
                "name": "COMPARISON_CONFIG",
                "value": "clusterVersion.json podLatency.json podCPU-avg.json podCPU-max.json podMemory-avg.json podMemory-max.json"
            },
            {
                "_class": "hudson.model.TextParameterValue",
                "name": "ENV_VARS",
                "value": ""
            },
            {
                "_class": "hudson.model.BooleanParameterValue",
                "name": "INFRA_WORKLOAD_INSTALL",
                "value": true
            },
            {
                "_class": "hudson.model.StringParameterValue",
                "name": "SCALE_UP",
                "value": "7"
            },
            {
                "_class": "hudson.model.StringParameterValue",
                "name": "SCALE_DOWN",
                "value": "0"
            },
            {
                "_class": "hudson.model.StringParameterValue",
                "name": "E2E_BENCHMARKING_REPO",
                "value": "https://github.com/cloud-bulldozer/e2e-benchmarking"
            },
            {
                "_class": "hudson.model.StringParameterValue",
                "name": "E2E_BENCHMARKING_REPO_BRANCH",
                "value": "master"
            }
        ]
    },
```

2022-06-03 17:28 UTC, nathan-weinberg commented
/cc @paigerube14

2022-06-03 17:43 UTC, memodi commented
could we remove `_class ` parameter from all jenkins job parameters? I don't think that's of any use to us.

2022-06-03 18:16 UTC, memodi requested changes

2022-06-03 18:16 UTC, memodi commented on scripts/nope.py
> +	if DEBUG:
python's logging module should help if we're using this condition all around for debug print statements.

2022-06-03 18:16 UTC, memodi commented on scripts/README.md
> +4. From `performance-dashboards/dittybopper`, run `$ ./deploy.sh -t /tmp/netobserv-dittybopper.yaml`
add a step to import dashboard onto grafana

2022-06-03 18:32 UTC, nathan-weinberg commented on scripts/nope.py
> +	if DEBUG:
i'll look into it!

2022-06-04 16:18 UTC, nathan-weinberg commented on scripts/nope.py
> +	parser.add_argument("--jenkins-job", type=str, help='Jenkins job name to associate with run')
@memodi Just `scale-ci` or `scale-ci/e2e-benchmarking-multibranch-pipeline`?

2022-06-06 13:49 UTC, memodi commented on scripts/nope.py
> +	parser.add_argument("--jenkins-job", type=str, help='Jenkins job name to associate with run')
I think we can hardcode `scale-ci/e2e-benchmarking-multibranch-pipeline` and use `jenkins-job` argument to specify just the  branch job it ran with under `e2e-benchmarking-multibranch-pipeline`

2022-06-06 15:13 UTC, nathan-weinberg commented
New example with `--jenkins-job kube-burner` and `--jenkins-build 491`:

```json
{
    "benchmarkEnv": {
        "uuid": "fef07925-d342-4879-a500-1e9c8f7e0d10",
        "jenkins_job_params": [
            {
                "name": "BUILD_NUMBER",
                "value": "108879"
            },
            {
                "name": "WORKLOAD",
                "value": "node-density-heavy"
            },
```
etc etc

2022-06-06 18:27 UTC, paigerube14 commented on scripts/README.md
> +export PROMETHEUS_USER_WORKLOAD_BEARER=$(oc sa get-token prometheus-user-workload -n openshift-user-workload-monitoring)
Get this error when running the prometheus bearer token command 

```
 % export PROMETHEUS_USER_WORKLOAD_BEARER=$(oc sa get-token prometheus-user-workload -n openshift-user-workload-monitoring)
export THANOS_URL=https://`oc get route thanos-querier -n openshift-monitoring -o json | jq -r '.spec.host'`
error: could not find a service account token for service account "prometheus-user-workload"
```

2022-06-06 18:29 UTC, paigerube14 commented on scripts/README.md
> +export PROMETHEUS_USER_WORKLOAD_BEARER=$(oc sa get-token prometheus-user-workload -n openshift-user-workload-monitoring)
Might need something like this line now: https://github.com/cloud-bulldozer/e2e-benchmarking/blob/64d4ca22c4395aad0b9be7230c48029207d945e8/workloads/kube-burner/common.sh#L15

Is the prometheus-user-workload sa created somewhere in the set-up scripts?

2022-06-06 18:35 UTC, paigerube14 commented on scripts/README.md
> +export PROMETHEUS_USER_WORKLOAD_BEARER=$(oc sa get-token prometheus-user-workload -n openshift-user-workload-monitoring)
Not sure if you saw my link, but think you now have to generate a bearer token like the link above. Can OR if a token doesn't already exist

2022-06-06 18:39 UTC, paigerube14 commented on scripts/nope.py
> +	parser.add_argument("--jenkins-build", type=str, help='Jenkins build number to associate with run')
I would try to document these nope arguments somewhere. It isn't clear from the README currently that nope has all these options

2022-06-06 18:42 UTC, nathan-weinberg commented on scripts/nope.py
> +	parser.add_argument("--jenkins-build", type=str, help='Jenkins build number to associate with run')
@paigerube14 maybe I could add a note saying to run `./nope.py --help` to view all command line options?

2022-06-06 18:48 UTC, paigerube14 commented on scripts/nope.py
> +	parser.add_argument("--jenkins-build", type=str, help='Jenkins build number to associate with run')
Definitely! For the jenkins-job and jenkins-build varaibles it's not super clear on the distinction between them. And will this tool allow the option for running in not the main e2e-multibranch pipeline? Is that part of the jenkins-job parameter you pass? 
I know in jenkins there's an environment built in variable called BUILD_URL which might be useful when calling this tool from within a Jenkins job. Might be easier to just pass the full URL than separating it out into job type and build number

2022-06-06 19:09 UTC, memodi commented on scripts/README.md
> +export PROMETHEUS_USER_WORKLOAD_BEARER=$(oc sa get-token prometheus-user-workload -n openshift-user-workload-monitoring)
interesting. Yes we should add a OR condition in the script, @nathan-weinberg - do you want to add it as part of this PR?

2022-06-06 19:12 UTC, nathan-weinberg commented on scripts/nope.py
> +	parser.add_argument("--jenkins-build", type=str, help='Jenkins build number to associate with run')
@paigerube14 addressing your points:
1. `jenkins-job` is the job name (e.g. `kube-burner`) and `jenkins-build` is the job's build number `e.g. 491`
2. At @memodi's request it is hardcoded to use the main e2e-multibranch pipeline - I'd like to introduce the ability to run NetObserv tests from this pipeline if possible, I'll ping you elsewhere wrt that
3. @memodi and I discussed how we wanted to pass these variables, we went with this approach as we want the tool to be able to be used locally and not just within a Jenkins env

2022-06-06 19:16 UTC, nathan-weinberg commented on scripts/README.md
> +export PROMETHEUS_USER_WORKLOAD_BEARER=$(oc sa get-token prometheus-user-workload -n openshift-user-workload-monitoring)
Yes @memodi can do! What would the OR condition look like in our usecase?

2022-06-06 19:18 UTC, paigerube14 commented on scripts/README.md
> +export PROMETHEUS_USER_WORKLOAD_BEARER=$(oc sa get-token prometheus-user-workload -n openshift-user-workload-monitoring)
export PROMETHEUS_USER_WORKLOAD_BEARER =$(oc sa get-token -n openshift-user-workload-monitoring prometheus-user-workload || oc sa new-token -n openshift-user-workload-monitoring prometheus-user-workload)

2022-06-06 19:20 UTC, memodi commented on scripts/README.md
> +export PROMETHEUS_USER_WORKLOAD_BEARER=$(oc sa get-token prometheus-user-workload -n openshift-user-workload-monitoring)
I think it should look like:
`oc sa get-token prometheus-user-workload -n openshift-user-workload-monitoring || oc sa new-token prometheus-user-workload -n openshift-user-workload-monitoring`

2022-06-06 19:22 UTC, nathan-weinberg commented on scripts/README.md
> +export PROMETHEUS_USER_WORKLOAD_BEARER=$(oc sa get-token prometheus-user-workload -n openshift-user-workload-monitoring)
glad you both put the same thing - that's good QE ;)

2022-06-06 20:14 UTC, memodi approved these changes
/lgtm

2022-06-06 20:17 UTC, merged