Adding cerberus core
openshift-qe/ocp-qe-perfscale-ci pull request #238
Opened 2022-08-25 16:19 UTC by paigerube14

Adding in setting CERBERUS_CORES based on the number of projects 

## Issue

During execution of checking the cluster status with over 150 projects on the cluster the agent is becoming disconnected because the cores are getting overloaded 

This is currently always failing when running cluster-density tests with over 100 iterations (applicable when doing medium scale testing)

2022-08-25 16:19 UTC, paigerube14 commented
Passing job when having over 200 created projects: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/cerberus/216/console

2022-08-26 16:09 UTC, paigerube14 commented
/assign @nathan-weinberg 
/assign @svetsa-rh 
/assign @qiliRedHat

2022-08-26 16:20 UTC, nathan-weinberg requested changes

2022-08-26 16:20 UTC, nathan-weinberg commented on Jenkinsfile
> +            defaultValue:'oc411',
```suggestion
            name: 'JENKINS_AGENT_LABEL',
            defaultValue: 'oc411',
```

2022-08-26 16:20 UTC, nathan-weinberg commented on Jenkinsfile
> +            description:'You can change this to point to your fork if needed.'
```suggestion
            defaultValue: 'https://github.com/redhat-chaos/cerberus',
            description: 'You can change this to point to your fork if needed.'
```

2022-08-26 16:20 UTC, nathan-weinberg commented on Jenkinsfile
> +            description:'You can change this to point to a branch on your fork if needed.'
```suggestion
            defaultValue: 'main', 
            description: 'You can change this to point to a branch on your fork if needed.'
```

2022-08-26 16:24 UTC, nathan-weinberg commented
/lgtm

2022-08-29 03:22 UTC, qiliRedHat commented
/lgtm

2022-08-29 03:25 UTC, merged