Added upload mode to NOPE tool
openshift-qe/ocp-qe-perfscale-ci pull request #269
Opened 2022-09-23 17:10 UTC by nathan-weinberg

Resolves [NETOBSERV-596](https://issues.redhat.com/browse/NETOBSERV-596)

2022-09-23 17:10 UTC, nathan-weinberg commented
/hold for testing

2022-09-23 17:11 UTC, nathan-weinberg commented
//c @memodi @Amoghrd

2022-09-23 17:16 UTC, nathan-weinberg commented
Successfully tested locally:
```bash
[nathan@nathan-redhat scripts (netobserv-perf-tests)]$ ./nope.py --upload-file data_2022-09-21_14-40-05.json
INFO:root:Running NOPE tool in Upload mode - data from /home/nathan/ocp/ci/ocp-qe-perfscale-ci/data/data_2022-09-21_14-40-05.json will be uploaded to Elasticsearch
INFO:elasticsearch:POST https://search-ocp-qe-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com:443/netobserv-perf/_doc [status:201 request:0.428s]
INFO:elasticsearch:POST https://search-ocp-qe-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com:443/netobserv-perf/_doc [status:201 request:0.067s]
INFO:elasticsearch:POST https://search-ocp-qe-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com:443/netobserv-perf/_doc [status:201 request:0.113s]
...
```

2022-09-23 17:17 UTC, nathan-weinberg commented
/unhold

2022-09-23 17:17 UTC, nathan-weinberg commented
/cc @memodi @Amoghrd

2022-09-23 17:49 UTC, memodi commented
@nathan-weinberg - I was thinking about this feature as sometimes uploads might fail transiently and by the time we get to it cluster is no longer available. 
I wonder, if capturing data in JSON prior to upload would be a good idea and having that archived as Jenkins artifacts so that we can upload locally even in cases where cluster dies later, WDYT?

2022-09-23 17:51 UTC, nathan-weinberg commented
> @nathan-weinberg - I was thinking about this feature as sometimes uploads might fail transiently and by the time we get to it cluster is no longer available. I wonder, if capturing data in JSON prior to upload would be a good idea and having that archived as Jenkins artifacts so that we can upload locally even in cases where cluster dies later, WDYT?

This already happens in Jenkins - if an upload fails the file is dumped to artifacts and can be downloaded/upload to ES manually

2022-09-23 17:53 UTC, memodi commented
> > @nathan-weinberg - I was thinking about this feature as sometimes uploads might fail transiently and by the time we get to it cluster is no longer available. I wonder, if capturing data in JSON prior to upload would be a good idea and having that archived as Jenkins artifacts so that we can upload locally even in cases where cluster dies later, WDYT?
> 
> This already happens in Jenkins - if an upload fails the file is dumped to artifacts and can be downloaded/upload to ES manually

Awesome, thanks!

2022-09-23 18:16 UTC, memodi requested changes
as CLI args grows suggest to use argsparse argument groups.

2022-09-23 18:16 UTC, memodi commented on scripts/nope.py
> +    parser.add_argument("--starttime", type=str, help='Start time for range query')
a better approach would be use argsparse [argument groups](https://docs.python.org/3/library/argparse.html#argument-groups), where you can have these has required arguments if in non-upload mode.

2022-09-23 18:16 UTC, memodi commented on scripts/nope.py
> +    if UPLOAD_FILE != '':
```suggestion
    if UPLOAD_FILE is not None:
```

I am getting error as:
```
$ ./nope.py
Traceback (most recent call last):
  File "/Users/memodi/workspaces/repos/ocp-qe-perfscale-ci/scripts/./nope.py", line 339, in <module>
    upload_file_path = DATA_DIR + '/' + UPLOAD_FILE
TypeError: can only concatenate str (not "NoneType") to str
```

it would be also better to print `help` showing all arguments if no arguments are passed.

2022-09-23 18:16 UTC, memodi commented on scripts/nope.py
> +    if START_TIME == '' or END_TIME == '':
if you use argsparse arguments groups, you won't need to add such conditions, argsparse would handle it for you.

2022-09-23 18:39 UTC, nathan-weinberg commented on scripts/nope.py
> +    parser.add_argument("--starttime", type=str, help='Start time for range query')
Ooh I hadn't heard of this, will check it out!

2022-09-23 18:42 UTC, memodi commented on scripts/nope.py
> +    parser.add_argument("--starttime", type=str, help='Start time for range query')
I use this in [jenkins_remote.py](https://github.com/memodi/tools/blob/master/jenkins_remote/jenkins_remote.py#L131) if you need reference

2022-09-26 13:26 UTC, nathan-weinberg commented on scripts/nope.py
> +    if START_TIME == '' or END_TIME == '':
Actually I think we still need it, argparse doesn't seem to handle multiple exclusive groups well

2022-09-26 16:27 UTC, memodi requested changes
some more comments

2022-09-26 16:27 UTC, memodi commented on scripts/nope.py
> +    upload.add_argument("--upload-file", type=str, default='', help='JSON file to upload to Elasticsearch. Must be in the "data" directory. Note this flag runs the NOPE tool in Upload mode and causes
can we use the absolute user provided path instead of being very strict about where the UPLOAD_FILE should be located?

2022-09-26 16:27 UTC, memodi commented on scripts/nope.py
> +        upload_file_path = DATA_DIR + '/' + UPLOAD_FILE
if we use user provided path then this won't be needed I think

2022-09-26 16:44 UTC, nathan-weinberg commented on scripts/nope.py
> +    else:
See my previous comments

2022-09-26 16:44 UTC, nathan-weinberg commented on scripts/nope.py
> +    upload.add_argument("--upload-file", type=str, default='', help='JSON file to upload to Elasticsearch. Must be in the "data" directory. Note this flag runs the NOPE tool in Upload mode and causes
Data should be saved in that path anyway, so IMO it makes sense to upload from there as well. We can always enhance this later.

2022-09-26 16:45 UTC, nathan-weinberg commented on scripts/nope.py
> +        upload_file_path = DATA_DIR + '/' + UPLOAD_FILE
See previous comments

2022-09-26 16:52 UTC, memodi commented on scripts/nope.py
> +    standard.add_argument("--endtime", type=str, help='End time for range query')
right, they're not required if running with `--upload--file`, however when I am running in standard mode, I get this error if I don't specify those args, I run into this ugly exception:
```
$ ./nope.py
Traceback (most recent call last):
  File "/Users/memodi/workspaces/repos/ocp-qe-perfscale-ci/scripts/./nope.py", line 369, in <module>
    logging.info("Parsed Start Time: " + datetime.datetime.fromtimestamp(int(START_TIME)).strftime('%I:%M%p%Z UTC on %m/%d/%Y'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
since you're also checking for https://github.com/openshift-qe/ocp-qe-perfscale-ci/blob/259486569cf8f6025f80bb11bfbfd1369da1592a/scripts/nope.py#L365-L367 , having `--required=True` for this args makes sense and we can get rid of these lines to simplify code a bit.

> Actually I think we still need it, argparse doesn't seem to handle multiple exclusive groups well
could you share what issues you ran into?

2022-09-26 17:40 UTC, nathan-weinberg commented on scripts/nope.py
> +    standard.add_argument("--endtime", type=str, help='End time for range query')
You can't have two exclusive argparse groups each with required arguments, and you can't use `required` with an argument if it's part of an exclusive group

As for the error, yes it's not pretty but tbh I'm not sure I see the value in handholding users for an internal tool that have not followed the README steps

2022-09-27 02:27 UTC, memodi commented on scripts/nope.py
> +    standard.add_argument("--endtime", type=str, help='End time for range query')
okay, sounds good to me.

2022-09-27 02:27 UTC, memodi commented
/lgtm

2022-09-27 02:31 UTC, merged