Updated Jenkinsfile and shell scripts, some CRD configs
openshift-qe/ocp-qe-perfscale-ci pull request #317
Opened 2022-11-09 22:28 UTC by nathan-weinberg

This PR makes the following changes:
- Simplifies Jenkinsfile with additional template directions and scripting moved to the shell scripts
- Removed need for $WORKSPACE variable if running `netobserv.sh` scripts locally
- Updated shell scripts with additional logging and minor functionality changes
- Added `nukeobserv` function to completely remove all NetObserv artifacts from a cluster
- Updated CRDs by changing `cacheMaxFlows` value for eBFP

2022-11-10 15:05 UTC, nathan-weinberg commented
/cc @memodi @paigerube14 @mffiedler

2022-11-10 23:37 UTC, memodi requested changes

2022-11-11 03:49 UTC, nathan-weinberg commented on scripts/flows_v1alpha1_flowcollector_lokistack.yaml
> +      cacheMaxFlows: 100000
For sure - for both files or just this one?

2022-11-11 04:21 UTC, nathan-weinberg commented on scripts/nope.py
> +        logging.info("Parsed End Time:   " + datetime.datetime.utcfromtimestamp(int(END_TIME)).strftime('%I:%M%p%Z UTC on %m/%d/%Y'))
Yup, would change timestamp display to show localized time, which is EST locally for us and UTC for Jenkins. Now it should be consistent

2022-11-11 15:34 UTC, memodi commented on scripts/flows_v1alpha1_flowcollector_lokistack.yaml
> +      cacheMaxFlows: 100000
just this one. This is newly added.

2022-11-11 15:35 UTC, memodi commented
> New installation steps can be seen succeeding here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/232/

@nathan-weinberg - does this PR address where user may already have NetObserv but wishes to update some params? if so, could you have that as a success run as well? thanks

2022-11-11 15:41 UTC, memodi commented
> Sure, do you have a cluster I can use?
unfortunately not the Flexy cluster

2022-11-11 15:42 UTC, nathan-weinberg commented
> > Sure, do you have a cluster I can use?
> 
> unfortunately not the Flexy cluster

Flexy is disabled, so we probably would not be able to do this until Monday

2022-11-11 16:42 UTC, memodi commented
> Flexy is disabled, so we probably would not be able to do this until Monday

I was able to get one created luckily, Flexy id: 155078 , let me know when you're done there!

2022-11-11 17:17 UTC, memodi commented
> I was able to get one created luckily, Flexy id: 155078 , let me know when you're done there!
actually this is the incorrect one, I am building one now since Jenkins is back now.

2022-11-11 18:04 UTC, nathan-weinberg commented
Unfortunately we are still seeing issues with Flexy - I will update this PR will successful test jobs ASAP

2022-11-14 20:01 UTC, nathan-weinberg commented
Successful Jobs:
- Initial Install: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/239/
- Updated Config: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/240/

2022-11-15 15:00 UTC, memodi commented
/lgtm

2022-11-15 15:04 UTC, merged