Adding ability to install official released NetObserv operator
openshift-qe/ocp-qe-perfscale-ci pull request #340
Opened 2023-01-18 15:50 UTC by nathan-weinberg

Resolves [OCPQE-13592](https://issues.redhat.com/browse/OCPQE-13592)

2023-01-18 18:27 UTC, nathan-weinberg commented
/cc @memodi @Amoghrd

2023-01-18 18:28 UTC, nathan-weinberg commented
Successful Runs:
`Official`: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/354/
`Internal`: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/355/
`OperatorHub`: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/357
`Source`: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/359/

2023-01-18 21:26 UTC, Amoghrd reviewed
loki.querierUrl is not required I think. Its not being used in backend automation

2023-01-20 19:26 UTC, memodi requested changes
@nathan-weinberg - LGTM, just one minor nit on file naming, let me know wdyt.

2023-01-20 20:44 UTC, nathan-weinberg commented on scripts/netobserv.sh
> +  FLOWCOLLECTOR=$SCRIPTS_DIR/flowcollector/flows_v1alpha1_flowcollector_released_lokistack.yaml
Agreed - will make the change

2023-01-20 21:54 UTC, memodi approved these changes
/lgtm

2023-01-20 21:58 UTC, merged