Made configuration of NOO and FLP resources optional
openshift-qe/ocp-qe-perfscale-ci pull request #394
Opened 2023-03-22 20:04 UTC by nathan-weinberg

Tested here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/78/

2023-03-22 20:10 UTC, nathan-weinberg commented
Additional test here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/83/

2023-03-22 20:50 UTC, memodi requested changes

2023-03-22 20:50 UTC, memodi commented on Jenkinsfile
>          )
I think defaulting sampling to 1 is fine, we should mostly use 1 for our testing.

2023-03-22 20:50 UTC, memodi commented on Jenkinsfile
> +                            oc patch flowcollector cluster --type=json -p "[{"op": "replace", "path": "/spec/agent/ebpf/sampling", "value": ${params.FLP_SAMPLING_RATE}}] -n netobserv"
always patch for sampling to bring it to 1.

2023-03-23 14:02 UTC, nathan-weinberg commented on Jenkinsfile
>          )
Ack, will leave that default in

2023-03-23 14:28 UTC, memodi commented on Jenkinsfile
> +                            oc patch flowcollector cluster --type=json -p "[{"op": "replace", "path": "/spec/agent/ebpf/sampling", "value": ${params.FLP_SAMPLING_RATE}}] -n netobserv"
in that case you'd always have to patch, no? so no need for if condition there since `FLP_SAMPLING_RATE` will always be set..

2023-03-23 15:06 UTC, memodi commented
/lgtm

2023-03-23 15:11 UTC, merged