Consolidated some CRDs and updated operator NS
openshift-qe/ocp-qe-perfscale-ci pull request #397
Opened 2023-03-27 15:14 UTC by nathan-weinberg

Changes made:
- the CRD organization was a little inconsistent, so I've done a slight reorg:
  - Removed `subscriptions` directory and moved subscriptions to the directory pertaining to **the specific operator** (amq-streams was already like this)
  - Added `netobserv` directory for all NetObserv-specifc CRDs (subscriptions, operatorgroup, and FlowCollector CRD)
-  Updated references to `openshift-operators` to `openshift-netobserv-operators` **pertaining to NetObserv Operator**

2023-03-29 21:05 UTC, nathan-weinberg commented
E2E test job (others are available as well, see the other runs from my fork): https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/106/

2023-03-29 21:06 UTC, nathan-weinberg commented
/cc @memodi @Amoghrd

2023-03-30 21:14 UTC, memodi requested changes
few minor comments, overall looks good.

2023-03-30 21:14 UTC, memodi commented on scripts/netobserv.sh
> +  oc delete crd/flowcollectors.flows.netobserv.io
don't delete crd here here.. this should be in `delete_netobserv` after deleting csv..

2023-03-30 21:14 UTC, memodi commented on scripts/netobserv.sh
>    oc delete project netobserv
add delete for project `openshift-netobserv-operator` NS as well

2023-03-30 21:14 UTC, memodi commented on scripts/netobserv/netobserv-internal-subscription.yaml
>    channel: v1.0.x
should be move to "stable" channel because it's already introduced and v1.0.x will be gone after 1.2.0

2023-03-30 21:14 UTC, memodi commented on scripts/netobserv/netobserv-operatorgroup.yaml
> +apiVersion: v1
rename this file for it includes more than just operatorgroup, perhaps `netobserv_ns_og_rolebindigs.yaml`?

2023-03-30 21:18 UTC, nathan-weinberg commented on scripts/netobserv.sh
> +  oc delete crd/flowcollectors.flows.netobserv.io
will be fixed in next patchset

2023-03-30 21:19 UTC, nathan-weinberg commented on scripts/netobserv.sh
>    oc delete project netobserv
will be fixed in next patchset

2023-03-30 21:20 UTC, nathan-weinberg commented on scripts/netobserv/netobserv-internal-subscription.yaml
>    channel: v1.0.x
will be fixed in next patchset

2023-03-30 21:20 UTC, memodi commented
@nathan-weinberg  we should also change api to be `v1beat1` [here](https://github.com/openshift-qe/ocp-qe-perfscale-ci/blob/netobserv-perf-tests/scripts/flows_v1alpha1_flowcollector.yaml#L1)

2023-03-30 21:28 UTC, memodi commented on scripts/netobserv/netobserv-ns_rb_og.yaml.yaml
extra `.yaml` in file name

2023-03-30 21:28 UTC, nathan-weinberg commented on scripts/netobserv/netobserv-ns_rb_og.yaml.yaml
whoops

2023-03-31 13:49 UTC, nathan-weinberg commented on scripts/netobserv.sh
>    oc delete project netobserv
removed this again as it's part of a previous deletion (the `ns_rb_og` file)

2023-03-31 13:59 UTC, Amoghrd commented
Tried an install, it works as expected!
/lgtm

2023-03-31 14:04 UTC, merged