Made Sandman output configurable
openshift-qe/ocp-qe-perfscale-ci pull request #476
Opened 2023-07-06 22:09 UTC by nathan-weinberg

Building off of https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/470 this PR does the following:
- adds a `.gitignore` for Sandman-related artifacts
- adds in the `README.md` blurb being removed in https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/475
- allows users to config which output file type they wish to specify between `json` and `sh` - since currently teams are only using JSON, this field is optional and defaults to JSON, but we may want to explore adding additional file types as well such as YAML sometime in the future

2023-07-06 22:10 UTC, nathan-weinberg commented
/cc @paigerube14

2023-07-07 00:20 UTC, nathan-weinberg commented
I tried out a more holistic update for the `main` branch `README` - lmk your thoughts @mffiedler @paigerube14 - can always revert to the previous commit

2023-07-07 18:35 UTC, memodi commented on scripts/sandman.py
> +    parser.add_argument("--output", type=str, default='json', help="Sandman out file type - options are 'json' (default) and 'sh'")
looking at the description of the arg, I don't know what 'sh' is? I can figure out if I looked in code, it will write bunch of variables to sh script but won't be able to understand if I didn't know code.  Is there a need for multiple file format? if there's really a need for both then perhaps we should explain it better.

2023-07-07 18:39 UTC, memodi requested changes
just couple of comments,

2023-07-07 18:39 UTC, memodi commented on scripts/sandman.py
> +    if SANDMAN_OUT_FILE_TYPE not in ['json', 'sh']:
within parse.add_argument you can have `choices`, argsparse will throw exception if its outside of those choices and no need for `if` condition

2023-07-07 19:53 UTC, nathan-weinberg commented on scripts/sandman.py
> +    parser.add_argument("--output", type=str, default='json', help="Sandman out file type - options are 'json' (default) and 'sh'")
@memodi that functionality was already added by @paigerube14, this just makes it into an option

2023-07-07 19:56 UTC, nathan-weinberg commented on scripts/sandman.py
> +    if SANDMAN_OUT_FILE_TYPE not in ['json', 'sh']:
nice tip!

2023-07-07 19:57 UTC, paigerube14 commented on README.md
> +Sometimes, the only way to get data such as UUID and workload timestamp information is directly from the workload job runs. If you find yourself in need of this but don't want to manually pour throug
Want to add file type option here

2023-07-07 20:08 UTC, nathan-weinberg commented on README.md
> +Sometimes, the only way to get data such as UUID and workload timestamp information is directly from the workload job runs. If you find yourself in need of this but don't want to manually pour throug
Done!

2023-07-07 20:09 UTC, nathan-weinberg commented on scripts/sandman.py
> +    parser.add_argument("--output", type=str, default='json', help="Sandman out file type - options are 'json' (default) and 'sh'")
Clarified in the `README`

2023-07-07 20:10 UTC, paigerube14 commented
looks good!

2023-07-07 20:35 UTC, memodi commented
/lgtm

2023-07-10 13:45 UTC, paigerube14 commented
/lgtm

2023-07-10 13:49 UTC, merged