Add performance baseline functionality to NOPE tool
openshift-qe/ocp-qe-perfscale-ci pull request #493
Opened 2023-08-02 20:36 UTC by nathan-weinberg

2023-08-07 13:44 UTC, nathan-weinberg commented
Code/functionality will be demoed in today's NO QE Sync

2023-08-08 14:39 UTC, paigerube14 commented
Wonder if you should separate out this functionality into its own script. Seems like the nope script does a lot of different things

2023-08-08 14:43 UTC, memodi requested changes
minor comments on `argparse` but overall looks good. Thanks!

2023-08-08 14:51 UTC, nathan-weinberg commented on scripts/nope.py
> +        logging.debug(f"Uploading item '{item}' to index '{index}' in Elasticsearch")
@memodi yes correct, made this change so it might be easier for users to see what fields are variables when analyzing logs, but open to suggestions around that as well!

2023-08-08 15:08 UTC, nathan-weinberg commented on scripts/nope.py
> +        sys.exit(0)
For sure, can change it to that - this will mean the following:
```
Note that currently mutually exclusive argument groups do not support the title and description arguments of add_argument_group()
```
Just want to confirm we are fine with that before making the change

2023-08-08 15:13 UTC, nathan-weinberg commented on scripts/nope.py
> +    baseline = parser.add_argument_group("Baseline Mode", "Fetch an existing baseline from Elasticsearch or Upload a new baseline")
Made a comment above, but if we go this direction yes I will be sure to do this

2023-08-08 15:19 UTC, memodi commented on scripts/nope.py
> +    elif BASELINE_TO_FETCH != '':
yeah, that's fine. No strong opinions.

2023-08-08 15:27 UTC, memodi commented on scripts/nope.py
> +        sys.exit(0)
Yeah, I think should be okay. Also, could we update Readme for `nope.py`

2023-08-08 15:46 UTC, nathan-weinberg commented on scripts/nope.py
> +        sys.exit(0)
Slight issue with this - it seems using this will require one of the baseline arguments to always be present, which won't work for us. Code below:
```python
# set baseline mode flags
baseline = parser.add_mutually_exclusive_group(required=True)
baseline.add_argument("--fetch-baseline", type=str, default='', help='Fetch the most recent baseline for a given workload')
baseline.add_argument("--upload-baseline", type=str, default='', help='Upload a new baseline for a given UUID')
```
And my attempt to run in upload mode (should fail on no argument for `--upload-file`):
```bash
[nathan@nathan-redhat scripts (netobserv-perf-tests)]$ ./nope.py --upload-mode
usage: nope.py [-h] [--debug] [--yaml-file YAML_FILE] [--starttime STARTTIME] [--endtime ENDTIME]
               [--step STEP] [--jenkins-job JENKINS_JOB] [--jenkins-build JENKINS_BUILD] [--uuid UUID]
               [--dump] [--jira JIRA] [--upload-file UPLOAD_FILE]
               (--fetch-baseline FETCH_BASELINE | --upload-baseline UPLOAD_BASELINE)
nope.py: error: one of the arguments --fetch-baseline --upload-baseline is required
```

2023-08-08 15:55 UTC, nathan-weinberg commented on scripts/nope.py
> +        sys.exit(0)
Right, but at that point I'm wondering if it's better to keep the current implementation since we already have an exclusivity check and we have this help guidance we otherwise wouldn't:
```bash
[nathan@nathan-redhat scripts (netobserv-perf-tests)]$ ./nope.py --help

...

Baseline Mode:
  Fetch an existing baseline from Elasticsearch or Upload a new baseline

  --fetch-baseline FETCH_BASELINE
                        Fetch the most recent baseline for a given workload
  --upload-baseline UPLOAD_BASELINE
                        Upload a new baseline for a given UUID
```

2023-08-08 15:56 UTC, memodi commented on scripts/nope.py
> +        sys.exit(0)
oh I somehow thought you're adding a subparser, therefore I suggested `required=True`.  When number of argument grows, you can categorize them by way of `subparser` to group arguments by sub-commands which lets you also specify mutually exclusive arguments specific to subparsers. See example, in case if you're interested https://github.com/memodi/tools/blob/master/jenkins_remote/jenkins_remote.py#L137

2023-08-08 16:00 UTC, nathan-weinberg commented on scripts/nope.py
> +        sys.exit(0)
Ooh okay I'll check this out! Will followup on Slack :+1:

2023-08-08 16:06 UTC, memodi commented on scripts/nope.py
> +        sys.exit(0)
looking at your argsparse code again, I think subparser is what you're looking for, since you're using `--upload-mode` to denote this is a different "functionality" being invoked, with subparser you can simply do `nope.py upload <--more sub-command-args>` . 

looking at all current args - should we rename the current "standard" mode -->  "upload" mode (uploads the metrics to ES) and current "upload" mode as "baseline" mode (forms and fetches the baseline) to reflect true functionalities, wdyt?

2023-08-08 16:18 UTC, nathan-weinberg commented on scripts/nope.py
> +        sys.exit(0)
Yeah I'm working on a subparser implementation right now, let me flesh this out a bit and I'll ping you about it and we can finalize some of the structure/wording :+1:

2023-08-08 18:06 UTC, nathan-weinberg commented
/hold

2023-08-08 19:51 UTC, nathan-weinberg commented
/unhold

2023-08-08 19:57 UTC, memodi commented
/lgtm

2023-08-08 20:00 UTC, merged