Add dynamic baselining to Jenkins job
openshift-qe/ocp-qe-perfscale-ci pull request #501
Opened 2023-08-15 14:34 UTC by nathan-weinberg

Resolves [NETOBSERV-1239](https://issues.redhat.com/browse/NETOBSERV-1239)

2023-08-15 15:53 UTC, nathan-weinberg commented
/cc @Amoghrd @paigerube14

2023-08-15 15:54 UTC, nathan-weinberg commented
Initially tested here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/379/

The fetching succeeded, but the upload remains untested as the Tolerancy Check failed (although the control flow did perform as expected)

Perhaps we should update our Tolerancy Config as part of this PR, as this will be the last update before cron scheduling, which will be configured via GitLab. Thoughts on that?

2023-08-15 15:55 UTC, nathan-weinberg commented
/hold

2023-08-17 14:50 UTC, nathan-weinberg commented on scripts/netobserv.sh
>      echo "====> To set config, set LOKISTACK_SIZE variable to either '1x.extra-small', '1x.small', or '1x.medium'"
Yup! Going to need to introduce the logic to determine whether or not we want `extra-small` or `demo` depending on Loki Operator version, but out-of-scope for this PR.

2023-08-17 19:56 UTC, memodi requested changes
looks good overall. I think we should hold off though as you suggested to wait for final approval for tolerancy configs from devs next week.

2023-08-17 19:56 UTC, memodi commented on scripts/queries/netobserv_touchstone_tolerancy_rules.yaml
>    max_failures: 0
could we add Loki and Kafka CPU, RSS totals as well? it would be very high tolerance value, say 60%, wdyt?

2023-08-17 19:56 UTC, memodi commented on scripts/analyze_metrics.py
> -import json
ah, I had forgotten about this script. good old times when we used to analyze data with this :D Long Live touchstone!!

2023-08-17 19:56 UTC, memodi commented on Jenkinsfile
> +                Note you will still need to check the box above to run the comparison
why RUN_BASELINE_COMPARISON checkbox needs to be checked, could we simply do comparison if UUID is specified?

2023-08-17 22:31 UTC, nathan-weinberg commented on scripts/queries/netobserv_touchstone_tolerancy_rules.yaml
>    max_failures: 0
Yes can do!

2023-08-17 22:32 UTC, nathan-weinberg commented on Jenkinsfile
> +                Note you will still need to check the box above to run the comparison
Checkbox determines if we want to run a comparison or not - if a UUID override is not provided the job uses the NOPE tool to dynamically fetch one for whatever workload was run

2023-08-22 19:17 UTC, memodi commented on scripts/queries/netobserv_touchstone_tolerancy_rules.yaml
> -  tolerancy: 2
thanks for updating these values, do you want to create a task to update nope tool to update with 0 value if nothing returns from Prometheus?

2023-08-22 19:22 UTC, nathan-weinberg commented on scripts/queries/netobserv_touchstone_tolerancy_rules.yaml
> -  tolerancy: 2
@memodi let's do as a followup, this PR is already quite large, I'll create a new task under the Enhancements story

2023-08-22 19:24 UTC, memodi commented on scripts/queries/netobserv_touchstone_tolerancy_rules.yaml
> -  tolerancy: 2
in the mean time we should continue to pay attention regular spreadsheet for flow errors/drops metrics.

2023-08-25 00:22 UTC, memodi commented
/lgtm

2023-08-25 00:25 UTC, merged