WIP: Pre-merge image patching
openshift-qe/ocp-qe-perfscale-ci pull request #552
Opened 2023-11-16 19:57 UTC by Amoghrd

2023-11-16 22:40 UTC, Amoghrd commented
Passing job : https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/aramesha-e2e-benchmarking-multibranch-pipeline/job/pre-merge/6/console

2023-11-17 14:09 UTC, Amoghrd commented
PTAL @nathan-weinberg

2023-11-17 16:13 UTC, nathan-weinberg requested changes
Seems something is up with the description population: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/aramesha-e2e-benchmarking-multibranch-pipeline/job/pre-merge/6/

2023-11-17 16:13 UTC, nathan-weinberg commented on scripts/README.md
> +
Can we populate this section?

2023-11-17 16:52 UTC, Amoghrd commented
I havent touched the description section in this code

2023-11-17 19:06 UTC, nathan-weinberg commented on scripts/README.md
> +If you want to install a premerge operator image that is present on quay.io instead of the `main` image, you can do so by setting the `$UPSTREAM_IMAGE` variable to the SHA hash of the premerge image,
`$UPSTREAM_IMAGE` should be `$OPERATOR_PREMERGE_OVERRIDE` I think

Also, I think we should call out that that one in particular requires selecting `Source` as your Installation Source, whereas I think the others can be done with any install method?

2023-11-17 19:14 UTC, Amoghrd commented on scripts/README.md
> +If you want to install a premerge operator image that is present on quay.io instead of the `main` image, you can do so by setting the `$UPSTREAM_IMAGE` variable to the SHA hash of the premerge image,
It doesnt matter that its source for operator too. Can be done with any installation method. Is there any reason to use for only source installation?

2023-11-20 16:07 UTC, nathan-weinberg commented on scripts/README.md
> +If you want to install a premerge operator image that is present on quay.io instead of the `main` image, you can do so by setting the `$UPSTREAM_IMAGE` variable to the SHA hash of the premerge image,
It does matter for the operator that it is `Source` - otherwise the proper Catalogsource won't be used - see https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/540

2023-11-20 16:36 UTC, Amoghrd commented on scripts/README.md
> +If you want to install a premerge operator image that is present on quay.io instead of the `main` image, you can do so by setting the `$UPSTREAM_IMAGE` variable to the SHA hash of the premerge image,
ah got it will update that

2023-11-20 16:48 UTC, nathan-weinberg approved these changes
/lgtm

2023-11-20 16:50 UTC, merged