change dump format to include raw_data
openshift-qe/ocp-qe-perfscale-ci pull request #590
Opened 2024-03-28 01:36 UTC by willr3

This changes the `--dump` json format to include the `raw_data` in `data` along with the `metric_name` and `query` that produced the `raw_data`. This also moves the `jenkins_env` and `netobserv_env` objects outside the `RESULST['data']` array to simplify processing when converting to `clean_data` for elastic search upload.

The goal of this change is to persist the data from the System Under Test (SUT) in a format that closely matches the format from the underlying tools (e.g. prometheus). This format will help support other tools' use of the data and decrease the json document size by decreasing the number of copies of the `metric` prometheus response field that is currently persisted in the `metadata` field. 

Note: Please check the PR as though it was written by a 5-year-old. I do not have an environment to test the python code and about half the time I had to correct myself from trying to write in javascript notation (.e.g `RESULTS.data` instead of `RESULTS['data']`)

2024-03-28 21:49 UTC, nathan-weinberg commented on scripts/nope.py
> +    payload = {"data":[]}
I'm thinking we might not need to use the `data` var at all here but could just initialize the `payload` as an empty list, see my other comment below

2024-03-28 21:49 UTC, nathan-weinberg commented on scripts/nope.py
> +    '''
```suggestion
    ''' formats the data in RESULTS into a de-normalized payload for elasticsearch
        returns a dict with the de-normalized list under the 'data' key
    '''
```
JS/Python terms :wink: but if we go the approach I suggest below we could just do
```suggestion
    ''' formats the data in RESULTS into a de-normalized list for elasticsearch upload compatability
    '''
```

2024-03-28 21:49 UTC, nathan-weinberg commented on scripts/nope.py
> +        RESULTS["data"].append({"raw_data": raw_data, "query" : query, "metric_name" : metric_name})
```suggestion
        RESULTS["prometheus_data"].append({"raw_data": raw_data, "query" : query, "metric_name" : metric_name})
```

2024-03-28 21:49 UTC, nathan-weinberg commented on scripts/nope.py
> +    for item in formatted['data']:
```suggestion
    for item in documents:
```

2024-03-28 21:49 UTC, nathan-weinberg commented on scripts/nope.py
> +    formatted = format_for_upload()
```suggestion
    documents = format_data_for_upload()
```

2024-03-28 21:49 UTC, nathan-weinberg commented on scripts/nope.py
> +def format_for_upload():
```suggestion
def format_data_for_upload():
```

2024-03-28 21:49 UTC, nathan-weinberg commented on scripts/nope.py
> +            payload["data"].extend(clean_data)
```suggestion
    if 'jenkins_env' in RESULTS:
        payload.append(RESULTS['jenkins_env'])
    if 'netobserv_env' in RESULTS:
        payload.append(RESULTS['netobserv_env'])
    if 'prometheus_data' in RESULTS and len(RESULTS['prometheus_data']) > 0:
        for item in RESULTS['prometheus_data']:
            clean_data = process_query(item['metric_name'], item['query'], item['raw_data'])
            payload["prometheus_data"].extend(clean_data)
```

2024-03-29 11:18 UTC, willr3 commented on scripts/nope.py
> +    payload = {"data":[]}
I agree, no need to complicate the internal representation. I commited the recommended changes. Do you want me to squash them back into a single commit and rebase?

2024-03-29 14:58 UTC, nathan-weinberg commented on scripts/nope.py
> +    payload = {"data":[]}
@willr3 Nah no need for backwards compatibility with the old format, I will retest the changes today if I can, early next week at the latest - appreciate the updates!

2024-03-31 21:39 UTC, nathan-weinberg requested changes
@willr3 I found one bug with ES uploading where UUID isn't be recorded for the datapoints - my suggestions should fix it but if you notice anything amiss with the logic lmk

2024-03-31 21:39 UTC, nathan-weinberg commented on scripts/nope.py
> +            clean_data = process_query(item['metric_name'], item['query'], item['raw_data'])
```suggestion
            clean_data = process_query(
                uuid,
                item['metric_name'],
                item['query'],
                item['raw_data']
            )
```

2024-03-31 21:39 UTC, nathan-weinberg commented on scripts/nope.py
> +        payload.append(RESULTS['netobserv_env'])
```suggestion
    if 'jenkins_env' in RESULTS:
        payload.append(RESULTS['jenkins_env'])
        uuid = RESULTS['jenkins_env]['uuid']
    if 'netobserv_env' in RESULTS:
        payload.append(RESULTS['netobserv_env'])
        if uuid is None:
            uuid =  RESULTS['netobserv_env']['uuid']
        else:
            assert uuid == RESULTS['netobserv_env']['uuid'], "UUIDs for jenkinsEnv and netobservEnv did not match, data may be malformed"
```

2024-03-31 21:39 UTC, nathan-weinberg commented on scripts/nope.py
> +    payload = []
```suggestion
    uuid = None
    payload = []
```

2024-03-31 21:39 UTC, nathan-weinberg commented on scripts/nope.py
> +
Can remove extra space here

2024-03-31 21:42 UTC, nathan-weinberg commented
Following changes would be needed to `process_query` as well (basically just add new `uuid` param)
```python
def process_query(uuid, metric_name, query, raw_data):
    ''' takes in a UUID, Prometheus metric name, query and its successful execution result
        reformats data into format desired for Elasticsearch upload
        returns dict object with post-processed data
    '''

    # intialize post-processing data object
    clean_data = []

    # capture metadata and value artifacts from prometheus return object
    try:
        for result in raw_data["data"]["result"]:
            for data_point in result["values"]:
                metadata = result["metric"]
                metadata["query"] = query
                iso_timestamp = get_iso_timestamp(data_point[0])
                clean_data.append(
                    {
                        "uuid": uuid,
                        "metric_name": metric_name,
                        "data_type": "datapoint",
                        "iso_timestamp": iso_timestamp,
                        "unix_timestamp": data_point[0],
                        "value": float(data_point[1]),
                        "metadata": metadata
                    }
                )
```

2024-04-01 02:12 UTC, willr3 commented
Excellent catch on the `uuid` I updated the PR with the fix to `process_query` and the spacing comment as well as the other discussions you raised. 
Do we want `NOPE` to be able to work with older dump formats?

2024-04-01 02:20 UTC, willr3 commented on scripts/nope.py
> +
I removed the extra line in the newest update

2024-04-01 14:41 UTC, nathan-weinberg commented
> Excellent catch on the `uuid` I updated the PR with the fix to `process_query` and the spacing comment as well as the other discussions you raised. Do we want `NOPE` to be able to work with older dump formats?

Nah don't think we'll need that - I did find one issue with the code changes that needs to be fixed, see my comment above

2024-04-01 17:55 UTC, nathan-weinberg approved these changes
Full test run: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-dump-raw/15/

Things are looking good to me, want my colleagues to review before merging but as it stands I'm happy with this on my side.

2024-04-01 17:55 UTC, nathan-weinberg commented
/cc @memodi @Amoghrd

2024-04-01 17:55 UTC, nathan-weinberg commented
/cc @mffiedler @paigerube14 (for reference)

2024-04-01 19:24 UTC, memodi approved these changes
code changes look good to me.

2024-04-01 19:46 UTC, merged