NETOBSERV-1744: Kafka replicas update
openshift-qe/ocp-qe-perfscale-ci pull request #615
Opened 2024-07-02 17:46 UTC by Amoghrd

PR has following changes:
- Update kafkaReplicas
- Make kafkaReplicas variable update values based on workload
- Remove references to router-perf and cluster-density

2024-07-02 17:55 UTC, memodi requested changes

2024-07-02 17:55 UTC, memodi commented on Jenkinsfile
> +            choices: ['None', 'cluster-density-v2', 'cluster-density', 'node-density-heavy', 'ingress-perf'],
```suggestion
            choices: ['None', 'cluster-density-v2', 'node-density-heavy', 'ingress-perf'],
```

2024-07-02 17:55 UTC, memodi commented on Jenkinsfile
> +                If empty, job will automatically set value based on the workload run<br/>
```suggestion
                <b>Leave this empty if you're triggering standard perf-workloads, default of 6, 12 and 18 FLP_KAFKA_REPLICAS will be used for node-density-heavy, ingress-perf and cluster-density-v2 workloads respectively</b><br/>
                3 - for non-perf testing environments<br/>
                <b>Use this field to overwrite default FLP_KAFKA_REPLICAS</b><br/>
```

2024-07-02 18:31 UTC, memodi commented
@Amoghrd - can you trigger a test run on your branch for ndh to make sure it's working as expected? Also, please rebase this PR, I see several merge commits.

2024-07-03 20:05 UTC, Amoghrd commented
Perf run failed but the params were passed correctly [job#15](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/aramesha-e2e-benchmarking-multibranch-pipeline/job/kafkaReplicas/15/console)

2024-07-03 20:13 UTC, memodi approved these changes
/lgtm
thanks @Amoghrd

2024-07-03 20:16 UTC, merged